# -*- coding: utf-8 -*-
"""Pixcap_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11a-8b5HrlrmlmVTuIQauBr8FiYtU8rXG
"""

import torch
print(torch.cuda.is_available())

!pip install transformers
!pip install pillow

from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
import torch
from PIL import Image
from google.colab import files

model_name = "nlpconnect/vit-gpt2-image-captioning"

model = VisionEncoderDecoderModel.from_pretrained(model_name)
processor = ViTImageProcessor.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

uploaded = files.upload()

image = Image.open(list(uploaded.keys())
[0]).convert("RGB")

pixel_values = processor(images=image, return_tensors="pt").pixel_values
pixel_values = pixel_values.to(device)

output_ids = model.generate(pixel_values, max_length=20, num_beams=4)
caption = tokenizer.decode(output_ids[0], skip_special_tokens=True)

print("Basic Caption:")
print(caption)

import random

def catchy_caption(base_caption):

    styles = [
        f"{base_caption.capitalize()} — but make it iconic ✨",
        f"Serving views and vibes 😎",
        f"Proof that moments like this exist 🌍",
        f"Main character energy right here 🎬",
        f"{base_caption.capitalize()}, but make it aesthetic 📸",
        f"Caught in a frame, living in a vibe 💫",
        f"Where history meets the sky ⏳",
        f"Just out here creating memories 🧡"
    ]

    return random.choice(styles)


def smart_hashtags(base_caption):
    keywords = base_caption.split()
    tags = ["#" + word for word in keywords if len(word) > 3]
    tags += ["#InstaVibes", "#ExploreMore", "#TravelGram"]
    return " ".join(tags[:6])


print("\n✨ Catchy Caption:")
print(catchy_caption(caption))

print("\n🔥 Hashtags:")
print(smart_hashtags(caption))

def trendy_caption(base_caption):
    return base_caption + " ✨ Timeless vibes!"

def emoji_caption(base_caption):
    return base_caption + " 🏛️⏰"

def aesthetic_caption(base_caption):
    return "Lost in the beauty of " + base_caption

def hashtag_generator(base_caption):
    words = base_caption.split()
    hashtags = ["#" + word for word in words[:3]]
    return " ".join(hashtags)

print("\nTrendy Caption:")
print(trendy_caption(caption))

print("\nEmoji Caption:")
print(emoji_caption(caption))

print("\nAesthetic Caption:")
print(aesthetic_caption(caption))

print("\nHashtags:")
print(hashtag_generator(caption))

import matplotlib.pyplot as plt

plt.imshow(image)
plt.axis("off")
plt.title("Uploaded Image")
plt.show()

def mood_caption(base_caption, mood):

    if mood == "Travel":
        return f"Wander often, wonder always 🌍 | {base_caption}"

    elif mood == "Aesthetic":
        return f"Soft lights & timeless sights ✨ | {base_caption}"

    elif mood == "Savage":
        return f"Built different. Built iconic 😎 | {base_caption}"

    elif mood == "Motivation":
        return f"Every moment counts ⏳ | {base_caption}"

    else:
        return base_caption


mood = "Travel"   # Change mood here

print("\nMood Based Caption:")
print(mood_caption(caption, mood))

mood = "Aesthetic"

print("="*50)
print("✨ PixCap - AI Caption Generator ✨")
print("="*50)

print("\n📌 Basic:")
print(caption)

print("\n🔥 Catchy:")
print(catchy_caption(caption))

print("\n🎭 Mood Style:")
print(mood_caption(caption, "Aesthetic"))

print("\n#️⃣ Hashtags:")
print(smart_hashtags(caption))

print("="*50)